[2024-12-23T04:05:13.030+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T04:05:13.045+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-23T04:05:13.054+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-23T04:05:13.055+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T04:05:13.070+0600] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_weather_data> on 2024-12-21 00:00:00+00:00
[2024-12-23T04:05:13.076+0600] {standard_task_runner.py:72} INFO - Started process 48348 to run task
[2024-12-23T04:05:13.081+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_et_pipeline', 'extract_weather_data', 'scheduled__2024-12-21T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_pipeline.py', '--cfg-path', '/tmp/tmpkqnzjx5j']
[2024-12-23T04:05:13.082+0600] {standard_task_runner.py:105} INFO - Job 7: Subtask extract_weather_data
[2024-12-23T04:05:13.135+0600] {task_command.py:467} INFO - Running <TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [running]> on host AbrarsPC
[2024-12-23T04:05:13.223+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_et_pipeline' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-21T00:00:00+00:00'
[2024-12-23T04:05:13.225+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-23T04:05:13.225+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-23T04:05:13.226+0600] {logging_mixin.py:190} INFO - Current task name:extract_weather_data state:running start_date:2024-12-22 22:05:13.046435+00:00
[2024-12-23T04:05:13.226+0600] {logging_mixin.py:190} INFO - Dag name:weather_et_pipeline and current dag run status:running
[2024-12-23T04:05:13.227+0600] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T04:05:13.241+0600] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/abr/airflow/dags/weather_etl_pipeline.py", line 40, in extract_weather_data
    response=http_hook.run(endpoint)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 170, in run
    session = self.get_conn(headers)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 110, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `open_mateo_api` isn't defined
[2024-12-23T04:05:13.247+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-12-23T04:05:13.248+0600] {logging_mixin.py:190} INFO - Task start:2024-12-22 22:05:13.046435+00:00 end:2024-12-22 22:05:13.247140+00:00 duration:0.200705
[2024-12-23T04:05:13.248+0600] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): extract_weather_data> dag:<DAG: weather_et_pipeline> dagrun:<DagRun weather_et_pipeline @ 2024-12-21 00:00:00+00:00: scheduled__2024-12-21T00:00:00+00:00, state:running, queued_at: 2024-12-22 22:05:09.611388+00:00. externally triggered: False>
[2024-12-23T04:05:13.248+0600] {logging_mixin.py:190} INFO - Failure caused by The conn_id `open_mateo_api` isn't defined
[2024-12-23T04:05:13.249+0600] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=weather_et_pipeline, task_id=extract_weather_data, run_id=scheduled__2024-12-21T00:00:00+00:00, execution_date=20241221T000000, start_date=20241222T220513, end_date=20241222T220513
[2024-12-23T04:05:13.263+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T04:05:13.264+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 7 for task extract_weather_data (The conn_id `open_mateo_api` isn't defined; 48348)
Traceback (most recent call last):
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/abr/airflow/dags/weather_etl_pipeline.py", line 40, in extract_weather_data
    response=http_hook.run(endpoint)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 170, in run
    session = self.get_conn(headers)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/providers/http/hooks/http.py", line 110, in get_conn
    conn = self.get_connection(self.http_conn_id)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/abr/Airfow/weather/airflow_env/lib/python3.10/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `open_mateo_api` isn't defined
[2024-12-23T04:05:13.293+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-23T04:05:13.320+0600] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T04:05:13.326+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-12-23T04:44:50.720+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T04:44:50.738+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-23T04:44:50.747+0600] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [queued]>
[2024-12-23T04:44:50.748+0600] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-12-23T04:44:50.765+0600] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): extract_weather_data> on 2024-12-21 00:00:00+00:00
[2024-12-23T04:44:50.771+0600] {standard_task_runner.py:72} INFO - Started process 53038 to run task
[2024-12-23T04:44:50.777+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'weather_et_pipeline', 'extract_weather_data', 'scheduled__2024-12-21T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/weather_etl_pipeline.py', '--cfg-path', '/tmp/tmpw92gm_sq']
[2024-12-23T04:44:50.778+0600] {standard_task_runner.py:105} INFO - Job 9: Subtask extract_weather_data
[2024-12-23T04:44:50.834+0600] {task_command.py:467} INFO - Running <TaskInstance: weather_et_pipeline.extract_weather_data scheduled__2024-12-21T00:00:00+00:00 [running]> on host AbrarsPC
[2024-12-23T04:44:50.941+0600] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='weather_et_pipeline' AIRFLOW_CTX_TASK_ID='extract_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-21T00:00:00+00:00'
[2024-12-23T04:44:50.943+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-12-23T04:44:50.944+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-12-23T04:44:50.945+0600] {logging_mixin.py:190} INFO - Current task name:extract_weather_data state:running start_date:2024-12-22 22:44:50.738534+00:00
[2024-12-23T04:44:50.945+0600] {logging_mixin.py:190} INFO - Dag name:weather_et_pipeline and current dag run status:running
[2024-12-23T04:44:50.945+0600] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T04:44:50.956+0600] {base.py:84} INFO - Retrieving connection 'open_meteo_api'
[2024-12-23T04:44:52.066+0600] {python.py:240} INFO - Done. Returned value was: {'latitude': 23.75, 'longitude': 90.375, 'generationtime_ms': 0.033020973205566406, 'utc_offset_seconds': 0, 'timezone': 'GMT', 'timezone_abbreviation': 'GMT', 'elevation': 19.0, 'current_weather_units': {'time': 'iso8601', 'interval': 'seconds', 'temperature': '°C', 'windspeed': 'km/h', 'winddirection': '°', 'is_day': '', 'weathercode': 'wmo code'}, 'current_weather': {'time': '2024-12-22T22:30', 'interval': 900, 'temperature': 15.8, 'windspeed': 3.7, 'winddirection': 349, 'is_day': 0, 'weathercode': 2}}
[2024-12-23T04:44:52.092+0600] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T04:44:52.093+0600] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_et_pipeline, task_id=extract_weather_data, run_id=scheduled__2024-12-21T00:00:00+00:00, execution_date=20241221T000000, start_date=20241222T224450, end_date=20241222T224452
[2024-12-23T04:44:52.104+0600] {logging_mixin.py:190} INFO - Task instance in success state
[2024-12-23T04:44:52.105+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-12-23T04:44:52.105+0600] {logging_mixin.py:190} INFO - Dag name:weather_et_pipeline queued_at:2024-12-22 22:44:46.973918+00:00
[2024-12-23T04:44:52.106+0600] {logging_mixin.py:190} INFO - Task hostname:AbrarsPC operator:_PythonDecoratedOperator
[2024-12-23T04:44:52.154+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T04:44:52.187+0600] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-23T04:44:52.191+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
